---
language: python
python: "2.7"

addons:
  ssh_known_hosts: 95.46.198.190

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad35a7dd52a2_key -iv $encrypted_ad35a7dd52a2_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - echo "Test."

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR root@95.46.198.190:/tmp/ -e "ssh -p 14321"
  on:
    branch: master
